### PR TITLE
expected project structure

### PR DESCRIPTION
**Pull request by yashasvimisra2798**
# Expected project structure

## Description of what's changing
It is adding the structure in which the code shall be organized within the repository

## What else might be impacted?
 It will help to segregate different implementations from the common code
 It will also allow us to easily expand the code owners in the future.

## Which issue does this PR relate to?
#17

## Checklist

[ ] Tests are written and maintain or improve code coverage
[ ] I've tested this in my application using `yarn link` (if applicable)
[x] You consent to and are confident this change can be released with no regression

### CODE REVIEW

**Comment by reubenae** [comment]
The formatting looks a bit weird when GitHub renders to markdown. I think you could try putting what you've added inside a code block. E.g. 

```
// project structure visual
```

image

**Comment by reubenae** [comment]
Otherwise it looks good! You can check the preview on your branch here https://github.com/yashasvimisra2798/user-data-for-fraud-prevention/tree/expected_project_structure#expected-project-structure

Feel free to re-open when you're ready :)

**Comment by yashasvimisra2798** [comment]
Yes I am trying to fix the formatting, will reopen it when I am done

**Comment by reubenae** [comment]
Try adding three backticks before the block, and three backticks after. Like this:

```
// Other readme part
```
  Project structure
```
// More readme
```

**Comment by yashasvimisra2798** [comment]
Thanks, @reubenae! I have made the changes please check.

**Comment by reubenae** [comment]
Looks great, thank you for contributing!

@all-contributors please add @yashasvimisra2798 for doc

**Pull request merged**
