### PR TITLE
feat: exporting screen and window details in hmrc files

### PR DESCRIPTION
**Pull request by JohanAludden**
# Exporting of window and screen details

## Description of what's changing
Added functions to get the screen and window details.
 
## What else might be impacted?
Nothing

## Which issue does this PR relate to?
issue #87 

## Checklist

[x] Tests are written and maintain or improve code coverage
[ ] I've tested this in my application using `yarn link` (if applicable)
[x] You consent to and are confident this change can be released with no regression

### CODE REVIEW

**Review by skodamarthi — COMMENTED** [review]
This makes me think what is the need to export only screen and window details while not exporting other details like timezone, browser plugins etc;

**Comment by JohanAludden** [comment]
> This makes me think what is the need to export only screen and window details while not exporting other details like timezone, browser plugins etc;

Yes, I noticed that the only data that we post process from this library are the values I exported. I do not think that the other values needs to be exported with the same granularity.

**Review by reubenae — APPROVED** [review]
I think I'm happy with this. I suppose you could argue that these should live in an encapsulated function with just a single import/export in index.js, but really this info is tied to MTD. The other option would be maybe to encapsulate them within an object e.g. `fraudRawData` so you'd do it as `import {fraudRawData} from 'user-data-for-fraud-prevention'` and use it like `fraudRawData.screenHeight()` - might clean up the API a bit. Thoughts @JohanAludden & @skodamarthi ?

**Comment by reubenae** [comment]
Also if you can rebase the CI job should pass, as you've added tests and code would like to have green CI checks

**Review by reubenae — APPROVED** [review]
LGTM

**Pull request merged**
