### PR TITLE
Migrate from sinon to jest spies

### PR DESCRIPTION
**Pull request by lucillewang**
# Migrate from sinon to jest spies

## Description of what's changing

Replaced all sinon spies with jest spies resolving issue listed here: https://github.com/intuit/user-data-for-fraud-prevention/issues/7

## What else might be impacted?

N/A

## Checklist

[ x] Tests are written and maintain or improve code coverage
[ x] I've tested this in my application using `yarn link` (if applicable)
[x ] You consent to and are confident this change can be released with no regression

### CODE REVIEW

**Comment by reubenae** [comment]
Hi @lucillewang ! Thanks for the contribution. Can you remove sinon from the dependencies too? https://github.com/lucillewang/user-data-for-fraud-prevention/blob/hacktoberfest-replace-sinon-with-jest/package.json#L67

**Review by reubenae — CHANGES_REQUESTED** [review]
Code changes look good, but I'd like to see sinon removed from the package.json too

**Comment by lucillewang** [comment]
Sinon has been removed from the package.json :)

**Comment by reubenae** [comment]
Thanks for your contribution Lucille! I am going to merge this but please be aware that it will not count towards hacktoberfest statistics. From the digital ocean website: 

> I signed up for Hacktoberfest mid-October. Will pull requests that I created earlier in October count?

> Yes, all pull requests created between Oct 1 and Oct 31 will count, regardless of when you register for Hacktoberfest. Pull requests created before Oct 1 but merged or marked as ready for review after do not count.

**Review by reubenae — APPROVED** [review]

**Pull request merged**
