### PR TITLE
Remove global utils file

### PR DESCRIPTION
**Pull request by jitinmaher**
# Title

## Description of what's changing
Remove global utils file and use jest globals instead for mocking

## What else might be impacted?

`src/js/common/browserInfoHelper.js`  is directly consuming the global object now

## Which issue does this PR relate to?

https://github.com/intuit/user-data-for-fraud-prevention/issues/34

## Checklist

[ ] Tests are written and maintain or improve code coverage
[ ] I've tested this in my application using `yarn link` (if applicable)
[ ] You consent to and are confident this change can be released with no regression

### CODE REVIEW

**Comment by jitinmaher** [comment]
@skodamarthi @reubenae Can you help with the review?

**Review by skodamarthi — CHANGES_REQUESTED** [review]
Changes look good! But please also delete globalsUtil file as part of this PR.

**Comment by jitinmaher** [comment]
@skodamarthi Forgot to delete that! Removed it in the latest commit

**Review by skodamarthi — APPROVED** [review]

**Comment by skodamarthi** [comment]
@jitinmaher Sorry merged by mistake before checking CI build status. Looks like unit tests are failing. I reverted your changes as part of https://github.com/intuit/user-data-for-fraud-prevention/pull/76. Can you please fix the tests and raise another PR?

**Comment by jitinmaher** [comment]
@skodamarthi Oh okay, The Pr didnt showed any failures. Will fix it and let you know. Thanks!

**Comment by jitinmaher** [comment]
@skodamarthi Raised another PR for the same here: https://github.com/intuit/user-data-for-fraud-prevention/pull/77

**Pull request merged**
