### PR TITLE
fix: change to strict equality operator for browserDoNotTrack status

### PR DESCRIPTION
**Pull request by skodamarthi**
# Title

## Description of what's changing

...

## What else might be impacted?

...

## Which issue does this PR relate to?

...

## Checklist

[ ] Tests are written and maintain or improve code coverage
[ ] I've tested this in my application using `yarn link` (if applicable)
[ ] You consent to and are confident this change can be released with no regression

### CODE REVIEW

**Review by reubenae — APPROVED** [review]

**Review by reubenae — COMMENTED** [review]
Actually I think Peter may be right with his comment here https://github.com/intuit/user-data-for-fraud-prevention/pull/182#discussion_r1009867463

Would be worth digging through the git history of the internal repo first to see if there was discussion over this originally?

**Comment by pmaidens** [comment]
Based off the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack), it seems like we should be able to change this to a `===` and be alright. Although, it might be a good idea to do some browser testing around this.

**Review by pmaidens — APPROVED** [review]

**Comment by reubenae** [comment]
I've approved but I'm going to leave clicking the big green button to @skodamarthi

**Pull request merged**
